### ISSUE TITLE
Не корректно удаляется тема

### ISSUE THREAD

**Issue by B3BECb** [B3BECb/textbooks#11]
Тема не удаляется, если ей принадлежит хотя бы 1 урок
![image](https://cloud.githubusercontent.com/assets/16418945/15102721/dc15c0a6-15b3-11e6-9594-11dcffd60d0b.png)

**Comment by dex35** [comment]
Странно, у меня столь ужасная ошибка не вылетает, но есть другая проблема.
Если теме принадлежит 1 урок - вылетает ошибка, если 2 - тема удаляется из директории, но дом элементы после обновления страницы остаются.

**Comment by B3BECb** [comment]
Да. Именно из-за наличия уроков она и возникает. По сути, не удаётся вызвать функцию removeDirectory из mainMenu.php в строке 45. 

Ну, эта ошибка столь ужасна из-за включенного у меня [xdebug](https://habrahabr.ru/post/250323/).

**Comment by dx88** [comment]
Стоит ли делать так? - is_dir($obj) ? removeDirectory($obj) : unlink($obj);
Когда можно так - is_dir($obj) ? rmdir($obj) : unlink($obj);

**Comment by dex35** [comment]
Ошибка решена, проблема была в цикле: 

```
foreach($objs as $obj)
{
is_dir($obj) ? $this->removeDirectory($obj) : unlink($obj);
}
```

Вызывали без $this->
